# Generated by Django 4.0.1 on 2022-02-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
