# Generated by Django 4.0.1 on 2022-02-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_category_categories_alter_categories_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/categories'),
        ),
    ]
