# Generated by Django 4.0.1 on 2022-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_remove_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sub-categories',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
