# Generated by Django 4.0.1 on 2022-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_sub_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
