# Generated by Django 4.0.1 on 2022-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
