# Generated by Django 4.0.1 on 2022-02-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_alter_sub_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
