# Generated by Django 4.0.2 on 2022-02-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_remove_category_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
    ]
