# Generated by Django 4.0.2 on 2022-02-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
