# Generated by Django 4.0.1 on 2022-02-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.IntegerField(null=True),
        ),
    ]
