# Generated by Django 4.0.2 on 2022-02-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_product_color_product_discount_product_final_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='sub_category_id',
        ),
    ]
