# Generated by Django 4.0.2 on 2022-03-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.FloatField(null=True),
        ),
    ]
